version: '3.4'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    networks:
      - front
      - backend
    depends_on:
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    networks:
      - front
    ports:
      - "3001:3000"

  postgres:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: todolist_development
      POSTGRES_HOST: host.docker.internal
    volumes:
      - db-cache:/var/lib/postgresql/data
    networks:
      - backend

networks:
  front:
  backend:

volumes:
  db-cache:

